[package]
name = "greenhouse"
version = "0.0.8"
authors = ["Felipe Penha <felipe.penha@alumni.usp.br>"]
description = "A Python containerized framework for a better Data X development workflow."
repository = "https://github.com/felipepenha/py-greenhouse"
license = "Apache-2.0"